<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => 'c0db9f858577ba4c355bf1148159ed65',
  'DATABASE_URL' => 'mysql://yuja2878_thot:imhotep_1939@127.0.0.1:3306/yuja2878_thot?serverVersion=10.6.19-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
