<?php

namespace Container2hxWP36;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerindexService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._CEMLIk.App\Controller\ArticleController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._CEMLIk.App\\Controller\\ArticleController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'genreRepo' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'genreRepo' => 'App\\Repository\\GenreRepository',
            'categorieRepo' => 'App\\Repository\\CategorieRepository',
        ]))->withContext('App\\Controller\\ArticleController::index()', $container);
    }
}
