<?php

namespace Container2hxWP36;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\API\\ArticleController::recherche' => ['privates', '.service_locator.IqSceiR.App\\Controller\\API\\ArticleController::recherche()', 'getArticleControllerrechercheService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator._CEMLIk.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.mBZG5U8.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController::showadmin' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::showadmin()', 'getArticleControllershowadminService', true],
            'App\\Controller\\ArticleController::edit' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\AuthentificationController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\CommentaireController::index' => ['privates', '.service_locator.hiFztTV.App\\Controller\\CommentaireController::index()', 'getCommentaireControllerindexService', true],
            'App\\Controller\\CommentaireController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CommentaireController::new()', 'getCommentaireControllernewService', true],
            'App\\Controller\\CommentaireController::show' => ['privates', '.service_locator.YbIxu0d.App\\Controller\\CommentaireController::show()', 'getCommentaireControllershowService', true],
            'App\\Controller\\CommentaireController::edit' => ['privates', '.service_locator.ags_qjM.App\\Controller\\CommentaireController::edit()', 'getCommentaireControllereditService', true],
            'App\\Controller\\CommentaireController::delete' => ['privates', '.service_locator.ags_qjM.App\\Controller\\CommentaireController::delete()', 'getCommentaireControllerdeleteService', true],
            'App\\Controller\\HomeController::tabadmin' => ['privates', '.service_locator.J_NkaF6.App\\Controller\\HomeController::tabadmin()', 'getHomeControllertabadminService', true],
            'App\\Controller\\HomeController::tabauteur' => ['privates', '.service_locator.naiiPlt.App\\Controller\\HomeController::tabauteur()', 'getHomeControllertabauteurService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.qKPbJaV.App\\Controller\\UtilisateurController::index()', 'getUtilisateurControllerindexService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.YcQzc6c.App\\Controller\\UtilisateurController::show()', 'getUtilisateurControllershowService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()', 'getUtilisateurControllereditService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.LVPv12D.App\\Controller\\UtilisateurController::delete()', 'getUtilisateurControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\API\\ArticleController:recherche' => ['privates', '.service_locator.IqSceiR.App\\Controller\\API\\ArticleController::recherche()', 'getArticleControllerrechercheService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator._CEMLIk.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.mBZG5U8.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController:showadmin' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::showadmin()', 'getArticleControllershowadminService', true],
            'App\\Controller\\ArticleController:edit' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.AazXZCq.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'App\\Controller\\AuthentificationController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\CommentaireController:index' => ['privates', '.service_locator.hiFztTV.App\\Controller\\CommentaireController::index()', 'getCommentaireControllerindexService', true],
            'App\\Controller\\CommentaireController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CommentaireController::new()', 'getCommentaireControllernewService', true],
            'App\\Controller\\CommentaireController:show' => ['privates', '.service_locator.YbIxu0d.App\\Controller\\CommentaireController::show()', 'getCommentaireControllershowService', true],
            'App\\Controller\\CommentaireController:edit' => ['privates', '.service_locator.ags_qjM.App\\Controller\\CommentaireController::edit()', 'getCommentaireControllereditService', true],
            'App\\Controller\\CommentaireController:delete' => ['privates', '.service_locator.ags_qjM.App\\Controller\\CommentaireController::delete()', 'getCommentaireControllerdeleteService', true],
            'App\\Controller\\HomeController:tabadmin' => ['privates', '.service_locator.J_NkaF6.App\\Controller\\HomeController::tabadmin()', 'getHomeControllertabadminService', true],
            'App\\Controller\\HomeController:tabauteur' => ['privates', '.service_locator.naiiPlt.App\\Controller\\HomeController::tabauteur()', 'getHomeControllertabauteurService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.g9BceMG.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.qKPbJaV.App\\Controller\\UtilisateurController::index()', 'getUtilisateurControllerindexService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.YcQzc6c.App\\Controller\\UtilisateurController::show()', 'getUtilisateurControllershowService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()', 'getUtilisateurControllereditService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.LVPv12D.App\\Controller\\UtilisateurController::delete()', 'getUtilisateurControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\API\\ArticleController::recherche' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::new' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ArticleController::showadmin' => '?',
            'App\\Controller\\ArticleController::edit' => '?',
            'App\\Controller\\ArticleController::delete' => '?',
            'App\\Controller\\AuthentificationController::login' => '?',
            'App\\Controller\\CommentaireController::index' => '?',
            'App\\Controller\\CommentaireController::new' => '?',
            'App\\Controller\\CommentaireController::show' => '?',
            'App\\Controller\\CommentaireController::edit' => '?',
            'App\\Controller\\CommentaireController::delete' => '?',
            'App\\Controller\\HomeController::tabadmin' => '?',
            'App\\Controller\\HomeController::tabauteur' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\API\\ArticleController:recherche' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:new' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ArticleController:showadmin' => '?',
            'App\\Controller\\ArticleController:edit' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
            'App\\Controller\\AuthentificationController:login' => '?',
            'App\\Controller\\CommentaireController:index' => '?',
            'App\\Controller\\CommentaireController:new' => '?',
            'App\\Controller\\CommentaireController:show' => '?',
            'App\\Controller\\CommentaireController:edit' => '?',
            'App\\Controller\\CommentaireController:delete' => '?',
            'App\\Controller\\HomeController:tabadmin' => '?',
            'App\\Controller\\HomeController:tabauteur' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
        ]));
    }
}
