<?php

namespace Container2hxWP36;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvatarRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AvatarRepository' shared autowired service.
     *
     * @return \App\Repository\AvatarRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AvatarRepository'] = new \App\Repository\AvatarRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
