<?php

namespace Container2hxWP36;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllerdeleteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ags_qjM.App\Controller\CommentaireController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ags_qjM.App\\Controller\\CommentaireController::delete()'] = ($container->privates['.service_locator.ags_qjM'] ?? $container->load('get_ServiceLocator_AgsQjMService'))->withContext('App\\Controller\\CommentaireController::delete()', $container);
    }
}
