<?php

namespace Container2hxWP36;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllereditService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ags_qjM.App\Controller\CommentaireController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.ags_qjM'] ?? $container->load('get_ServiceLocator_AgsQjMService'));

        if (isset($container->privates['.service_locator.ags_qjM.App\\Controller\\CommentaireController::edit()'])) {
            return $container->privates['.service_locator.ags_qjM.App\\Controller\\CommentaireController::edit()'];
        }

        return $container->privates['.service_locator.ags_qjM.App\\Controller\\CommentaireController::edit()'] = $a->withContext('App\\Controller\\CommentaireController::edit()', $container);
    }
}
