<?php

namespace Container2hxWP36;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllertabauteurService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.naiiPlt.App\Controller\HomeController::tabauteur()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.naiiPlt.App\\Controller\\HomeController::tabauteur()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
        ]))->withContext('App\\Controller\\HomeController::tabauteur()', $container);
    }
}
