<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2hxWP36\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2hxWP36/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container2hxWP36.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container2hxWP36\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container2hxWP36\App_KernelProdContainer([
    'container.build_hash' => '2hxWP36',
    'container.build_id' => 'f7c2eca4',
    'container.build_time' => 1728303830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2hxWP36');
